
package jframe;

import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
 import java.sql.*;

/**
 *
 * @author juans
 */

public class LoginPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginPage.class.getName());

    /**
     * Creates new form SignUpPage
     */
    public LoginPage() {
        initComponents();
    }
   
    //validate log in:
    
    public boolean validateLogin(){
        
        String username = txt_username.getText();
        String password = txt_password.getText();

    String errors = "";

    if (username.isEmpty()) errors += "- Please insert username\n";
    if (password.isEmpty()) errors += "- Please insert password\n";

    if (!errors.isEmpty()) {
        JOptionPane.showMessageDialog(this, errors, "Error", JOptionPane.ERROR_MESSAGE);
        return false;
    }

    return true;
}

    //verify credentials:
    
    public void logIn(){
        
        String username = txt_username.getText();
        String password = txt_password.getText();
        
        try {
            Connection con = DBConnection.getConnection();                      //MySQL connection
            
            PreparedStatement pst = con.prepareStatement("select * from users where username = ? and password = ?"); //sql instructions prepared 
            
            pst.setString(1, username);
            pst.setString(2, password);
            
            ResultSet rs = pst.executeQuery(); //executes the SQL instructions
            
            if (rs.next()){
                JOptionPane.showMessageDialog(this, "Log in successful. ✓", "Success",JOptionPane.INFORMATION_MESSAGE); //If  checkDuplicateusers = true throws error
                    
                HomePage home = new HomePage();
                home.setVisible(true);
                this.dispose();
                
            }
            else{
                JOptionPane.showMessageDialog(this, "Incorrect user or password", "Error",JOptionPane.ERROR_MESSAGE); //If  checkDuplicateusers = true throws error
            }
            
            con.close();
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }
    
    


    // Design Page:
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txt_username = new app.bolivia.swing.JCTextField();
        txt_password = new app.bolivia.swing.JCTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        button_minimize = new javax.swing.JButton();
        button_exit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        button_createaccount = new javax.swing.JButton();
        button_LogIn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Yu Gothic Medium", 0, 18)); // NOI18N
        jLabel3.setText("Juan Rincon Dev");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 150, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/library-3.png.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 770, 600));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 830));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI Semilight", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Sign In");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 230, 136, 46));

        txt_username.setBackground(new java.awt.Color(51, 51, 51));
        txt_username.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_username.setForeground(new java.awt.Color(255, 255, 255));
        txt_username.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txt_username.setPhColor(new java.awt.Color(255, 255, 255));
        txt_username.setPlaceholder("Enter Username...");
        txt_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_usernameFocusLost(evt);
            }
        });
        txt_username.addActionListener(this::txt_usernameActionPerformed);
        jPanel2.add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 340, -1));

        txt_password.setBackground(new java.awt.Color(51, 51, 51));
        txt_password.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        txt_password.setForeground(new java.awt.Color(255, 255, 255));
        txt_password.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 18)); // NOI18N
        txt_password.setPhColor(new java.awt.Color(255, 255, 255));
        txt_password.setPlaceholder("Enter Password...");
        txt_password.addActionListener(this::txt_passwordActionPerformed);
        jPanel2.add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 340, -1));

        jLabel11.setFont(new java.awt.Font("Yu Gothic Light", 1, 20)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Username");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 130, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("CAMI IS MY ENGINE");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 786, 220, 50));

        jLabel16.setFont(new java.awt.Font("Yu Gothic Light", 1, 20)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Password");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 460, 130, 40));

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 48)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Library Manager");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 116, 380, 112));

        button_minimize.setBackground(new java.awt.Color(51, 51, 51));
        button_minimize.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 24)); // NOI18N
        button_minimize.setForeground(new java.awt.Color(255, 255, 255));
        button_minimize.setText("-");
        button_minimize.setBorderPainted(false);
        button_minimize.setContentAreaFilled(false);
        button_minimize.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_minimize.setFocusPainted(false);
        button_minimize.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_minimizeMouseClicked(evt);
            }
        });
        button_minimize.addActionListener(this::button_minimizeActionPerformed);
        jPanel2.add(button_minimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 2, 48, 36));

        button_exit.setBackground(new java.awt.Color(51, 51, 51));
        button_exit.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 18)); // NOI18N
        button_exit.setForeground(new java.awt.Color(255, 255, 255));
        button_exit.setText("X");
        button_exit.setBorderPainted(false);
        button_exit.setContentAreaFilled(false);
        button_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        button_exit.setFocusPainted(false);
        button_exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_exitMouseClicked(evt);
            }
        });
        jPanel2.add(button_exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(478, 2, 50, -1));

        jLabel12.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Don't have an account?");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(94, 662, 260, 30));

        button_createaccount.setBackground(new java.awt.Color(51, 51, 51));
        button_createaccount.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 14)); // NOI18N
        button_createaccount.setForeground(new java.awt.Color(255, 255, 255));
        button_createaccount.setText("<html><font color='#a8d4ff'> <u>Create account</u></html>\n");
        button_createaccount.setBorderPainted(false);
        button_createaccount.setContentAreaFilled(false);
        button_createaccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel2.add(button_createaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 662, 188, -1));

        button_LogIn.setBackground(new java.awt.Color(204, 204, 204));
        button_LogIn.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 12)); // NOI18N
        button_LogIn.setForeground(new java.awt.Color(0, 0, 0));
        button_LogIn.setText("SIGN IN");
        button_LogIn.addActionListener(this::button_LogInActionPerformed);
        jPanel2.add(button_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 608, 340, 44));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 0, 530, 830));

        setSize(new java.awt.Dimension(1519, 828));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passwordActionPerformed

    private void txt_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_usernameActionPerformed

    private void button_exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_exitMouseClicked
        System.exit(0);                                                         //exit button
    }//GEN-LAST:event_button_exitMouseClicked

    private void button_minimizeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_minimizeMouseClicked
        this.setState(java.awt.Frame.ICONIFIED);                                //minimize button
    }//GEN-LAST:event_button_minimizeMouseClicked

    private void button_minimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_minimizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button_minimizeActionPerformed

    private void txt_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_usernameFocusLost

    }//GEN-LAST:event_txt_usernameFocusLost

    private void button_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_LogInActionPerformed
        if (validateLogin()){
            logIn();
        }
    }//GEN-LAST:event_button_LogInActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_LogIn;
    private javax.swing.JButton button_createaccount;
    private javax.swing.JButton button_exit;
    private javax.swing.JButton button_minimize;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private app.bolivia.swing.JCTextField txt_password;
    private app.bolivia.swing.JCTextField txt_username;
    // End of variables declaration//GEN-END:variables
}
